[package]
name = "bevy_tokio_runtime"
version = "0.2.0"
edition = "2021"

[dependencies]
bevy_app = { version = "0.11.3" }
bevy_ecs = { version = "0.11.3" }
tokio = { version = "1.32.0", features = ["rt-multi-thread", "sync"] }
