[package]
name = "bevy_tokio_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
bevy_app = "0.10.1"
bevy_ecs = "0.10.1"
crossbeam-channel = "0.5.8"
tokio = { version = "1.28.0", features = ["rt-multi-thread", "sync"] }
